class_name ShooterComponent
extends Node

## Handles shooting with advanced stat calculations in 3D.

# Default fallback scene for items that don't have a specific projectile_scene
@export var generic_projectile_scene: PackedScene
@export var projectile_speed: float = 600.0
@export var base_damage: float = 10.0
@export var base_element: ElementResource
@export var fire_rate: float = 1.0 
@export var fire_point_path: NodePath

# Made accessible for Turrets to calculate trajectory
@onready var fire_point: Marker3D = get_node_or_null(fire_point_path)

# Removed @onready to prevent crash if node is missing during procedural gen
var fire_rate_timer: Timer 

var _can_shoot: bool = true
var _parent_building: Node

func _ready() -> void:
	_parent_building = get_parent()
	
	# Load generic fallback if not set
	if not generic_projectile_scene:
		var fallback_path = "res://scenes/entities/projectile.tscn"
		if ResourceLoader.exists(fallback_path):
			generic_projectile_scene = load(fallback_path)

	if not fire_point and has_node("FirePoint"):
		fire_point = get_node("FirePoint")

	# If still no fire point, try to find one in children (often generated by importer)
	if not fire_point:
		fire_point = _parent_building.get_node_or_null("Rotatable/FirePoint")
		if not fire_point:
			fire_point = _parent_building.get_node_or_null("Rotatable/ProjectileOrigin")
		
	# Fallback to self if absolutely nothing found
	if not fire_point:
		# Create one dynamically at center up
		var m = Marker3D.new()
		m.name = "AutoFirePoint"
		m.position = Vector3(0, 0.5, 0)
		_parent_building.add_child(m)
		fire_point = m

	# Robust Timer Initialization
	fire_rate_timer = get_node_or_null("FireRateTimer")
	if not fire_rate_timer:
		fire_rate_timer = Timer.new()
		fire_rate_timer.name = "FireRateTimer"
		add_child(fire_rate_timer)

	fire_rate_timer.one_shot = true
	if not fire_rate_timer.timeout.is_connected(_on_fire_rate_timer_timeout):
		fire_rate_timer.timeout.connect(_on_fire_rate_timer_timeout)
		
	_update_timer()

func _update_timer() -> void:
	var speed_mult = 1.0
	if _parent_building and "stats" in _parent_building:
		speed_mult = _parent_building.stats.get("speed_mult", 1.0)
	
	if speed_mult <= 0: speed_mult = 0.1
	var rate = fire_rate * speed_mult
	if rate > 0:
		fire_rate_timer.wait_time = 1.0 / rate
	else:
		fire_rate_timer.wait_time = 999.0

func can_shoot() -> bool:
	return _can_shoot

func shoot_in_direction(direction: Vector3, target_lane_id: int, ammo_item: ItemResource = null, override_start_pos: Vector3 = Vector3.INF) -> void:
	if not _can_shoot: return
	
	var scene_to_spawn = generic_projectile_scene
	var texture_to_use = null
	var color_to_use = Color.WHITE
	
	var stats = {}
	if _parent_building and "stats" in _parent_building:
		stats = _parent_building.stats
	
	var final_damage = base_damage
	var element = base_element
	
	if ammo_item:
		final_damage += ammo_item.damage
		element = ammo_item.element
		texture_to_use = ammo_item.icon
		color_to_use = ammo_item.color
		
		# If item is a special projectile, use its scene
		if ammo_item.is_projectile and ammo_item.projectile_scene:
			scene_to_spawn = ammo_item.projectile_scene
		
	if not scene_to_spawn: return
	
	final_damage *= stats.get("damage_mult", 1.0)
	
	var is_crit = randf() < stats.get("crit_chance", 0.0)
	if is_crit:
		final_damage *= stats.get("crit_damage", 1.5)
		
	var proj = scene_to_spawn.instantiate()
	get_tree().current_scene.get_node("Projectiles").add_child(proj)
	
	var start = fire_point.global_position
	if override_start_pos != Vector3.INF: start = override_start_pos
	
	var extra_params = {
		"shred": stats.get("armor_shred", 0.0),
		"scale": stats.get("area_size", 1.0),
		"is_crit": is_crit
	}
	
	if proj.has_method("initialize"):
		proj.initialize(start, direction, projectile_speed, final_damage, target_lane_id, element, texture_to_use, color_to_use, false, extra_params)
	
	_can_shoot = false
	_update_timer()
	fire_rate_timer.start()

func _on_fire_rate_timer_timeout() -> void:
	_can_shoot = true
