class_name Projectile
extends Area3D

@export var default_scale: Vector3 = Vector3(0.5, 1.0, 0.5)
@export var visual_offset: Vector3 = Vector3(0, 0.0, 0) # Raise default Y

var _velocity: Vector3 = Vector3.ZERO
var _damage: float = 0.0
var _element: Resource = null
var _source_attacker: Node = null
var _attack_resource: AttackResource = null
var _element_units: int = 1
var _ignore_element_cd: bool = false
var lane_id: int = -1
var speed: float = 0.0
var lifetime: float = 5.0

var _hit_targets: Dictionary = {}
var _tick_timer: float = 0.0

@onready var sprite: Sprite3D = get_node_or_null("Sprite3D")

const OUTLINE_SHADER_CODE = """
shader_type spatial;
render_mode unshaded, cull_disabled, blend_mix; 
uniform sampler2D texture_albedo : source_color, filter_nearest;
uniform vec4 outline_color : source_color = vec4(1.0, 1.0, 1.0, 1.0);
uniform float width : hint_range(0.0, 10.0) = 1.0;
void fragment() {
	vec4 tex = texture(texture_albedo, UV);
	vec4 base_col = tex * COLOR; 
	vec2 size = vec2(textureSize(texture_albedo, 0));
	float px_x = width / size.x;
	float px_y = width / size.y;
	float a = texture(texture_albedo, UV + vec2(px_x, 0.0)).a;
	a += texture(texture_albedo, UV + vec2(-px_x, 0.0)).a;
	a += texture(texture_albedo, UV + vec2(0.0, px_y)).a;
	a += texture(texture_albedo, UV + vec2(0.0, -px_y)).a;
	if (base_col.a < 0.1 && a > 0.1) { ALBEDO = outline_color.rgb; ALPHA = 1.0; } 
	else { ALBEDO = base_col.rgb; ALPHA = base_col.a; if (base_col.a < 0.05) discard; }
}
"""

func _ready() -> void:
	collision_mask = 2 # Enemies
	collision_layer = 4 # Projectiles
	
	monitoring = true
	monitorable = true
	
	if sprite:
		sprite.scale = default_scale
		sprite.position = visual_offset

	# Hide fallback 2D sprite if a 3D model is present
	if has_node("Model") and sprite:
		sprite.visible = false

func _physics_process(delta: float) -> void:
	if _velocity == Vector3.ZERO:
		lifetime -= delta
		if lifetime <= 0: queue_free()
		return

	# Grid checks for Liquid stream momentum
	var current_speed_mult = 1.0
	var is_on_water = false
	var is_on_ink = false
	
	# Use standard SceneTree check for Autoloads instead of Engine C++ singletons
	if get_tree().root.has_node("LaneManager"):
		var current_tile = LaneManager.world_to_tile(global_position)
		var wire = LaneManager.get_entity_at(current_tile, "wire")
		var building = LaneManager.get_entity_at(current_tile, "building")
		
		# Streams are technically buildings, not wiring
		var stream = null
		if is_instance_valid(wire) and "display_name" in wire and wire.display_name in["Slipstream", "Tarstream"]:
			stream = wire
		elif is_instance_valid(building) and "display_name" in building and building.display_name in ["Slipstream", "Tarstream"]:
			stream = building
		
		if is_instance_valid(stream):
			var stream_name = stream.display_name
			if stream_name == "Slipstream":
				is_on_water = true
				if has_meta("ground_borne") or has_meta("sea_borne"):
					current_speed_mult = 2.0
			elif stream_name == "Tarstream":
				is_on_ink = true
				if has_meta("ground_borne") or has_meta("sea_borne"):
					current_speed_mult = 0.5
					
			if has_meta("sea_borne") and (is_on_water or is_on_ink):
				# Refresh grace period as long as it's correctly on the stream
				set_meta("grace_period", 0.5) 
				
				# Force the seaborne projectile (like Swans) to follow the stream's placed direction
				if "output_direction" in stream:
					var dir_idx = int(stream.output_direction)
					var new_dir = Vector3.ZERO
					if dir_idx == 0: new_dir = Vector3(0, 0, 1) # DOWN
					elif dir_idx == 1: new_dir = Vector3(-1, 0, 0) # LEFT
					elif dir_idx == 2: new_dir = Vector3(0, 0, -1) # UP
					elif dir_idx == 3: new_dir = Vector3(1, 0, 0) # RIGHT
					
					if new_dir != Vector3.ZERO:
						var current_dir = _velocity.normalized()
						# Verify if we reached a grid bend requiring a turn
						if new_dir.dot(current_dir) < 0.99:
							var tile_center = LaneManager.tile_to_world(current_tile)
							var to_center = tile_center - global_position
							to_center.y = 0
							# Check if we've crossed the very center of the stream intersection (Allow slight leniency)
							if current_dir.dot(to_center) <= 0.05:
								global_position.x = tile_center.x
								global_position.z = tile_center.z
								_velocity = new_dir.normalized() * speed
								look_at(global_position + _velocity, Vector3.UP)
						else:
							# Continue cleanly aligned
							_velocity = new_dir.normalized() * speed
				
	if has_meta("sea_borne") and get_meta("sea_borne"):
		if not is_on_water and not is_on_ink:
			# Swan/Lotus Folds instantly vanish outside of water trails (after initial launch grace period)
			var grace = float(get_meta("grace_period", 0.0))
			if grace > 0:
				set_meta("grace_period", grace - delta)
			else:
				queue_free()
				return

	global_position += (_velocity * current_speed_mult) * delta
	
	# Honor specific projectile lifetimes (ranges) generated by weapons/crafters
	if has_meta("lifetime"):
		var lf = float(get_meta("lifetime"))
		lf -= delta
		set_meta("lifetime", lf)
		if lf <= 0:
			queue_free()
			return
	else:
		lifetime -= delta
		if lifetime <= 0:
			queue_free()
			return
			
	# Ticking Damage processing
	if has_meta("tick_damage") and get_meta("tick_damage"):
		_tick_timer -= delta
		if _tick_timer <= 0:
			_tick_timer = 1.0
			if has_meta("aoe_explosion") and get_meta("aoe_explosion"):
				if get_tree().root.has_node("ElementManager"):
					ElementManager.apply_aoe_damage(self, 1.5, _damage, _source_attacker, false)
			else:
				for body in get_overlapping_bodies():
					_apply_damage_to(body)

	# 3D Specific Rotations for Origami Projectiles
	var model = get_node_or_null("Model")
	if model:
		var type = get_meta("fold_type", "")
		if type == "crumpled":
			model.rotate_x(-speed * delta * 0.5)
		elif type == "shuriken":
			model.rotate_y(15.0 * delta)

func initialize(start_pos: Vector3, dir: Vector3, p_speed: float, dmg: float, p_lane: int, p_elem: Resource = null, tex: Texture2D = null, col: Color = Color.WHITE, _use_path: bool = false, extra_params: Dictionary = {}) -> void:
	global_position = start_pos
	
	speed = p_speed * 0.02
	if speed < 2.0: speed = 10.0
	
	_velocity = dir.normalized() * speed
	_damage = dmg
	lane_id = p_lane
	_element = p_elem
	_source_attacker = extra_params.get("source", null)
	_attack_resource = extra_params.get("attack_resource", null)
	
	if extra_params.size() > 0:
		for k in extra_params.keys():
			set_meta(k, extra_params[k])
	
	# Parse explicit unit/CD data
	_element_units = extra_params.get("element_units", 1)
	_ignore_element_cd = extra_params.get("ignore_element_cd", false)
	
	if dir != Vector3.ZERO:
		look_at(global_position + dir, Vector3.UP)

	if sprite:
		sprite.position = visual_offset
		if tex: 
			sprite.texture = tex
			sprite.pixel_size = 0.04 # Make slightly bigger
			sprite.billboard = BaseMaterial3D.BILLBOARD_ENABLED
			sprite.axis = Vector3.AXIS_Y
		
		if _element and "color" in _element:
			sprite.modulate = _element.color
		else:
			sprite.modulate = col
			
		var s = extra_params.get("scale", 1.0)
		if typeof(s) == TYPE_FLOAT or typeof(s) == TYPE_INT:
			sprite.scale = default_scale * float(s)

		if tex:
			var shader = Shader.new()
			shader.code = OUTLINE_SHADER_CODE
			var mat = ShaderMaterial.new()
			mat.shader = shader 
			mat.set_shader_parameter("texture_albedo", tex)
			mat.resource_local_to_scene = true
			sprite.material_override = mat

	# Color 3D Meshes dynamically to match the element's aura!
	_color_meshes(self, col)

	if not body_entered.is_connected(_on_body_entered):
		body_entered.connect(_on_body_entered)

func _color_meshes(node: Node, col: Color) -> void:
	if node is MeshInstance3D:
		var mat = node.get_active_material(0)
		if not mat: 
			mat = StandardMaterial3D.new()
		else: 
			mat = mat.duplicate()
		mat.albedo_color = col
		node.set_surface_override_material(0, mat)
	for child in node.get_children():
		_color_meshes(child, col)

func _on_body_entered(body: Node3D) -> void:
	if not get_meta("tick_damage", false):
		if _hit_targets.has(body): return
		_hit_targets[body] = true
		
	var handled = _apply_damage_to(body)
	
	if handled:
		if get_meta("aoe_explosion", false):
			if not get_meta("tick_damage", false):
				if get_tree().root.has_node("ElementManager"):
					ElementManager.apply_aoe_damage(self, 1.5, _damage, _source_attacker, false)
				queue_free()
			return
			
		if not get_meta("piercing", false) and not get_meta("tick_damage", false):
			queue_free()

func _apply_damage_to(body: Node3D) -> bool:
	var valid_target = false
	if body is Enemy: valid_target = true
	elif body.has_method("take_damage"): valid_target = true
	elif body.has_node("HealthComponent"): valid_target = true
	
	if not valid_target: return false
	
	var e_lane = -1
	if body.has_method("get_lane_id"):
		e_lane = body.get_lane_id()
		
	if self.lane_id == -1 or e_lane == self.lane_id or e_lane == -1:
		var handled = false
		if _attack_resource and is_instance_valid(_source_attacker) and _source_attacker.has_node("AttackerComponent"):
			# Delegate damage/AoE logic to the attacker component
			var attacker = _source_attacker.get_node("AttackerComponent")
			attacker.call("_apply_hit", body, global_position, _damage, _attack_resource, _source_attacker)
			handled = true
			
		if not handled:
			if _element:
				# Pass new unit and cooldown parameters to ElementManager
				ElementManager.apply_element(body, _element, _source_attacker, _damage, _element_units, _ignore_element_cd)
			
			if body.has_method("take_damage"):
				body.take_damage(_damage, _element, _source_attacker)
			elif body.has_node("HealthComponent"):
				body.get_node("HealthComponent").take_damage(_damage, _element, _source_attacker)
				
			# Hook for ElementManager Reactions (e.g. Ripple / Conduct)
			if get_tree().root.has_node("ElementManager"):
				ElementManager.on_damage_dealt(body, _damage, _source_attacker)
			
		return true
	return false
